---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app

images:
  - name: "registry.k8s.io/kube-state-metrics/kube-state-metrics"
    newTag: "v2.9.2"
